language: rust

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev

rust:
- nightly
- beta
- stable

cache: cargo

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=lints

notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOK
    on_success: change
    on_failure: always
    on_start: never

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" == 'linux' ]; then
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
    elif [ "$TRAVIS_OS_NAME" == 'osx' ]; then
      echo 'travis-cargo is not supported on OS X builds.'
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == 'linux' ]; then
      travis-cargo build &&
      travis-cargo test
      travis-cargo --only stable doc
    else
      cargo build --verbose &&
      cargo test --verbose
    fi

after_success:
  - |
    if [ "$TRAVIS_OS_NAME" == 'linux' ]; then
      travis-cargo --only stable coveralls --no-sudo --verify
      travis-cargo --only stable doc-upload
    fi
