(function() {var implementors = {};
implementors['tutil'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='tutil/crayon/enum.Color.html' title='tutil::crayon::Color'>Color</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='tutil/crayon/struct.Style.html' title='tutil::crayon::Style'>Style</a>",];implementors['tutil'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='tutil/crayon/enum.Color.html' title='tutil::crayon::Color'>Color</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='tutil/crayon/struct.Style.html' title='tutil::crayon::Style'>Style</a>",];implementors['tutil'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='tutil/crayon/enum.Color.html' title='tutil::crayon::Color'>Color</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='tutil/crayon/struct.Style.html' title='tutil::crayon::Style'>Style</a>",];implementors['tutil'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='tutil/crayon/enum.Color.html' title='tutil::crayon::Color'>Color</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='tutil/crayon/struct.Style.html' title='tutil::crayon::Style'>Style</a>",];implementors['tutil'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='tutil/crayon/enum.Color.html' title='tutil::crayon::Color'>Color</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='tutil/crayon/struct.Style.html' title='tutil::crayon::Style'>Style</a>",];implementors['tutil'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='tutil/crayon/enum.Color.html' title='tutil::crayon::Color'>Color</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='tutil/crayon/struct.Style.html' title='tutil::crayon::Style'>Style</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
