(function() {var implementors = {};
implementors['tutil'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tutil/crayon/struct.StyledString.html' title='tutil::crayon::StyledString'>StyledString</a>&lt;'a&gt;",];implementors['tutil'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tutil/crayon/struct.StyledString.html' title='tutil::crayon::StyledString'>StyledString</a>&lt;'a&gt;",];implementors['tutil'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tutil/crayon/struct.StyledString.html' title='tutil::crayon::StyledString'>StyledString</a>&lt;'a&gt;",];implementors['tutil'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tutil/crayon/struct.StyledString.html' title='tutil::crayon::StyledString'>StyledString</a>&lt;'a&gt;",];implementors['tutil'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tutil/crayon/struct.StyledString.html' title='tutil::crayon::StyledString'>StyledString</a>&lt;'a&gt;",];implementors['tutil'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='tutil/crayon/struct.StyledString.html' title='tutil::crayon::StyledString'>StyledString</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
